apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}-nodeport-svc
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
    nodePort: {{ .Values.nodePort }}
  selector:
    app: {{ .Chart.Name }}
  type: NodePort
status:
  loadBalancer: {}
