name: Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - users-database
      - .github/workflows/users-database-build-and-deploy.yaml

env:
  DOCKER_REPOSITORY: europe-west1-docker.pkg.dev
  PROJECT_ID: galvanic-smoke-396218
  GOOGLE_CLOUD_SDK_VERSION: 444.0.0
  HELM_RELEASE: users-database
  GOOGLE_CLOUD_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT_JSON }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Google Cloud client
        run: |
          sudo apt purge --autoremove google-cloud-sdk
          curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-$GOOGLE_CLOUD_SDK_VERSION-linux-x86_64.tar.gz
          tar -xf google-cloud-cli-$GOOGLE_CLOUD_SDK_VERSION-linux-x86_64.tar.gz
          ./google-cloud-sdk/install.sh
          sudo ln -s $(pwd)/google-cloud-sdk/bin/gcloud /usr/local/bin/gcloud
          gcloud config set core/disable_usage_reporting true
          gcloud components update
          gcloud components install gke-gcloud-auth-plugin

      - name: Authenticate to Google Cloud
        run: |
          echo $GOOGLE_CLOUD_SERVICE_ACCOUNT_JSON > /tmp/service-account-key.json
          gcloud auth activate-service-account --quiet --key-file=/tmp/service-account-key.json
          gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://$DOCKER_REPOSITORY
          gcloud container clusters get-credentials vtts --region europe-west1 --project galvanic-smoke-396218

      - name: Install Helm
        run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Set Docker label and image name
        run: |
          echo "$DOCKER_REPOSITORY/galvanic-smoke-396218/vtts/users-database" > /tmp/image
          echo $(date +'%Y.%m.%d-%H%M%S') > /tmp/label

      - name: Build Docker image
        run: |
          export DOCKER_IMAGE="$(cat /tmp/image):$(cat /tmp/label)"
          echo $DOCKER_IMAGE
          echo $GOOGLE_CLOUD_SERVICE_ACCOUNT_JSON > ./users-database/.service-account-key.json
          docker build -t $DOCKER_IMAGE -f ./users-database/Dockerfile ./users-database
          docker push $DOCKER_IMAGE

      - name: Helm deploy
        run: |
          export LABEL=$(cat /tmp/label)
          helm upgrade --install --set-string dockerImageTag=$LABEL $HELM_RELEASE ./users-database/helm
